version: '3'

services:

  crossbar:
    image: crossbario/crossbar
    restart: always
    ports:
      - "8090:8080"

  db:
    image: postgres

  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - db
      - crossbar
    restart: always
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - SECRET_KEY=&_x8zn)ca^!#h!jt_pi9eo9y3p!evh9(_y9$$=3t@7r2jh+g2!#
      - CROSSBAR_REALM=realm1
      - CROSSBAR_URL=ws://crossbar:8080/ws
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Mount the app dir in the container as /src so our changes to the app code
      # are also changed in the container
      - .:/code


