# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auv', '0002_auv_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auvdata',
            options={'ordering': ('-created',)},
        ),
    ]
