# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv', '0003_auto_20160914_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='auv',
            name='update_frequency',
            field=models.FloatField(blank=True, help_text='Update frequency in [Hz]', null=True),
        ),
    ]
