# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auv', '0004_auv_update_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auv',
            name='max_depth',
        ),
        migrations.RemoveField(
            model_name='auv',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='auv',
            name='max_time_underwater',
        ),
        migrations.RemoveField(
            model_name='auv',
            name='serial_number',
        ),
    ]
