# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv', '0005_auto_20161016_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auvdata',
            old_name='temperature',
            new_name='air_temperature',
        ),
        migrations.AddField(
            model_name='auv',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('loiter', 'Loiter'), ('trip', 'Trip'), ('move_to_waypoint', 'Move To Waypoint')], default='manual', max_length=255),
        ),
        migrations.AddField(
            model_name='auvdata',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auvdata',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auvdata',
            name='water_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
