# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv', '0006_auto_20161016_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='auv',
            name='target_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auv',
            name='target_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auvdata',
            name='target_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auvdata',
            name='target_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
