# Generated by Django 2.1 on 2018-08-24 04:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auv', '0009_auto_20180821_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUVToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255)),
                ('token_hash', models.CharField(max_length=255)),
                ('auv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='auv.AUV')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
