# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20160916_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='auv',
        ),
        migrations.RemoveField(
            model_name='location',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
