# Generated by Django 2.1 on 2018-08-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20161016_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
